theme = "6160"

[editor]
line-number = "relative"
mouse = false
true-color = true
auto-completion = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# or control each character
[editor.whitespace.render]
tab = "all"
newline = "none"

[editor.whitespace.characters]
nbsp = "⍽"
tab = "→"
newline = "⏎"
